### ISSUE TITLE
User acitvity - The help option in help drop down is not functional.

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/ginger#347] opened 2016-05-17 12:24 UTC
#=== Problem Description ===================================
#===========================================================
The help option in help drop down in wok tab is not accessible.

**Comment by sureshab** [comment] 2016-06-03 06:17
@mesmriti 
this issue should be part of wok since "Activity log" is part of wok "Settings" tab. And the issue is fixed. Please confirm and close the issue.

**Closed** 2016-06-03 07:17 UTC
