### ISSUE TITLE
Global network Configuration does not retain data post navigation

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#153] opened 2016-01-08 17:12 UTC
Click Network→Global Network Configuration→ Add	

1. After adding IP address, navigate to any other tab and come back to Network section Added IP address is LOST
2. Above issue is same for Gateway IP Address also.

**Comment by sureshab** [comment] 2016-01-25 10:51
this could be duplicate of issue #180 
should be fixed by now..

**Comment by chandrureddy** [comment] 2016-01-25 10:57
HI Daniel, Please close this issue. This is already take care part of Issue #180

**Closed** 2016-01-25 11:01 UTC
Labels: backend, bug, UI
