### ISSUE TITLE
DNS field in Global Network configuration section is missing validation

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#370] opened 2016-07-18 11:58 UTC
DNS field is taking any value from ui.It's not shown as invalid field.Previously we used to validate  ipv4, ipv6 and hostname for DNS address. 

Current implementation:
![dns](https://cloud.githubusercontent.com/assets/13199397/16913990/50120dfe-4d0c-11e6-8aff-ca892747eaa0.jpg)

Previous implementation:
![dns](https://cloud.githubusercontent.com/assets/13199397/16914008/75777e80-4d0c-11e6-8ad6-aa932ab9781d.jpg)

**Comment by danielhb** [comment] 2016-12-02 19:05
Duplicate of https://github.com/kimchi-project/ginger/issues/447 which has been closed

**Closed by danielhb** 2016-12-02 19:05 UTC
