### ISSUE TITLE
GET operation of /plugins/ginger/network/cfginterfaces fails on s390x architecture

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#75] opened 2015-12-15 06:43 UTC
[root@zfwcec103 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces'
Enter host password for user 'root':
{
  "reason":"GINNET0015E: Error getting information from ifcfg file: ''Augeas' object has no attribute 'label''.",
  "code":"500 Internal Server Error"
}

**Comment by jay-katta** [comment] 2015-12-15 16:49
Its because of python-augeas old version doesn't have label method.
I have already raised bugzilla ticket to get python-augeas 0.5.0 version in zKVMIBM image.

**Comment by danielhb** [comment] 2015-12-15 17:38
Since this is not a bug inside Ginger, I'll close it

Thanks for the info @jay-katta !

**Closed by danielhb** 2015-12-15 17:38 UTC

**Comment by sureshab** [comment] 2015-12-16 06:32
the issues is valid for augeas version 0.5...please find more details below:

ls /usr/lib/python2.7/site-packages/ |grep 'aug*'
augeas.py
augeas.pyc
augeas.pyo
python_augeas-0.5.0-py2.7.egg-info
curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces'
Enter host password for user 'root':
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
}

Nothing was captured in error log.

**Comment by jay-katta** [comment] 2015-12-16 08:35
[root@zfwpc160 ginger]# ls /usr/lib/python2.7/site-packages/ |grep 'aug*'
augeas.py
augeas.pyc
augeas.pyo
python_augeas-0.5.0-py2.7.egg-info

curl -k -u root:pass4root -H "Content-Type: application/json" -H "Accept: application/json" 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces'
[
  {
    "IPV4_INFO":{
      "BOOTPROTO":"static",
      "DNSAddresses":[
        "9.152.120.241"
      ]
    },
    "BASIC_INFO":{
      "NAME":"enccw0.0.1810",
      "SUBCHANNELS":"0.0.1810,0.0.1811,0.0.1812",
      "OPTIONS":"\" layer2=1\"",
      "PORTNAME":"OSAPORT",
      "NETTYPE":"qeth",
      "DEVICE":"enccw0.0.1810",
      "TYPE":"Ethernet",
      "ONBOOT":"yes"
    },
    "IPV6_INFO":{}
  },
  {
    "IPV4_INFO":{},
    "BASIC_INFO":{
      "DEVICE":"lo",
      "NAME":"loopback",
      "ONBOOT":"yes"
    },
    "IPV6_INFO":{}
  },
  {},
  {}
]


Incase of "NAME" key is not available in the ifcfg file -

curl -k -u root:pass4root -H "Content-Type: application/json" -H "Accept: application/json" 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces'
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"

In the above case, error log says-

[16/Dec/2015:09:19:27] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 351, in index
    return self.get(filter_params)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 338, in get
    resources = self._get_resources(flag_filter)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 301, in _get_resources
    res.lookup()
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 146, in lookup
    self.info = lookup(*self.model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/cfginterfaces.py", line 265, in lookup
    info = self.get_cfginterface_info(name)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/cfginterfaces.py", line 387, in get_cfginterface_info
    ethinfo.update(self.get_interface_info(cfgmap))
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/cfginterfaces.py", line 393, in get_interface_info
    info.update(self.get_ipv4_info(info, cfgmap))
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/cfginterfaces.py", line 463, in get_ipv4_info
    routes = self.get_routes_map(cfgmap[NAME], 4)
KeyError: 'NAME'

For this issue refer Issue #77
