### ISSUE TITLE
Query: Minimum one DNS is mandatory on the system?

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/ginger#358] opened 2016-06-09 08:27 UTC
As per the current implementation for the DNS feature, API JSON schema is validating minimum one item.

        "network_update": {
            "type": "object",
            "properties": {
                "nameservers": {
                    "description": "DNS Servers",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "oneOf": [
                            { "format": "host-name" },
                            { "format": "ipv4" },
                            { "format": "ipv6" }
                        ]
                    },
                   "minItems": 1,
                    "uniqueItems": true,
                    "error": "GINNET0005E"
                },
                "gateway": {
                    "description": "Default network gateway",
                    "type": "string",
                    "format": "ip-address",
                    "error": "GINNET0008E"
                }
            }
        },

Having minimum one DNS is mandatory?

**Comment by danielhb** [comment] 2016-06-09 14:02
Having a DNS is helpful but we can't speculate of what the user want to do with his server. That includes not forcing at least one DNS server to be declared.

Feel free to patch API.json to not enforce this minimal value

**Comment by jay-katta** [comment] 2016-06-09 14:04
Sure, Thank you for your inputs

**Comment by alinefm** [comment] 2016-09-21 16:51
Closing issue as it was for a question not a bug.

**Closed** 2016-09-21 16:51 UTC
Labels: enhancement
