### ISSUE TITLE
GET partitoin fails with 500

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#168] opened 2016-01-09 19:29 UTC
[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://localhost:8001/plugins/ginger/partitions/invalid'
Enter host password for user 'root':
{
  "reason":"GINPART00003E: lookup method of partition failed",
  "code":"500 Internal Server Error"
}

**Comment by danielhb** [comment] 2016-01-13 00:30
Patch sent. Let me know if the issue is fixed, @sureshab

**Comment by sureshab** [comment] 2016-01-13 08:30
@danielhb 
i see still get 500,,not sure if am something here

[suresh@localhost ginger]$ curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://localhost:8001/plugins/ginger/partitions/invalid'
Enter host password for user 'root':
{
  "reason":"GINPART00003E: Error retrieving information of partition invalid : KCHDISKS0002E: KCHDISKS0002E",
  "code":"500 Internal Server Error"
}

i pulled latest ginger,,i executed api on x86 with fedora 21

**Comment by danielhb** [comment] 2016-01-13 08:52
I forgot to mention that this particular fix is dependent of a Gingerbase fix too

Can you try again with latest Gingerbase code?

**Comment by sureshab** [comment] 2016-01-13 09:07
oh!! gingerbase was not latest on my machine...
the fix works fine with latest ginger and gingerbase
[suresh@localhost gingerbase]$ curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://localhost:8001/plugins/ginger/partitions/invalid'
Enter host password for user 'root':
{
  "reason":"GINPART00014E: Partition invalid not found.",
  "code":"404 Not Found"
}

**Comment by danielhb** [comment] 2016-01-14 10:05
Alright, closing the issue. Thanks @sureshab

**Closed by danielhb** 2016-01-14 10:05 UTC
