### ISSUE TITLE
WOK:  Firmware update feature is getting displayed on x86 architecture

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/ginger#30] opened 2015-10-22 17:20 UTC
This bug was created for Kimchi project. But as it is related to Ginger I am moving it to here.
I didn't even tried to reproduce, I am only forwarding to the right project. =)

Please, check https://github.com/kimchi-project/kimchi/issues/709 for more details.

Environment: x86
Operating system: Ubuntu
Browser: Mozilla Firefox
Steps performed:
1. Installed WOK (https://github.com/kimchi-project/kimchi/tree/wok)
2. Installed kimchi-wok plugin
3. Installed ginger-wok plugin
2. Started wokd daemon
3. From browser launched https://127.0.0.1:8001
4. Login screen displayed
5. Entered userid and password
6. WOK web page displayed with Kimchi and Ginger tabs
7. Toggled between Administration tab(Ginger) and any Kimchi plugin tab

Problem: Power (ppc) firmware update feature is getting displayed

https://cloud.githubusercontent.com/assets/12508158/8746620/d6bed6f0-2ca8-11e5-91a5-23a8ff3ed529.jpg

**Comment by danielhb** [comment] 2015-10-27 19:53
I can't reproduce it in a Fedora 22 x86_64 machine and, seeing bug https://github.com/kimchi-project/kimchi/issues/709 , lcorreia wasn't able to reproduce it in his Ubuntu.

The bug is very old too (Jul 07). I'll test it in a Ubuntu VM and, if still unreproducible, I'll close the issue.

**Comment by danielhb** [comment] 2015-10-30 18:23
I've verified that the Firmware Update isn't being display in an Ubuntu 1504 running in x86_64, as expected.

I'll close it as 'Invalid'. Feel free to reopen this issue if you see it happening again.

Thanks

**Closed by danielhb** 2015-10-30 18:23 UTC
Labels: invalid
