### ISSUE TITLE
NW: PUT on /plugins/ginger/network/cfginterfaces/<interfacename> end with 500 when required parameters are missing

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/ginger#130] opened 2016-01-06 11:14 UTC
PUT operations on /plugins/ginger/network/cgfinterfaces/interfacename end with 500 when required parameters are not passed.
For e.g, When BASIC_INFO parameter is not passed in the curl command as shown below

curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X PUT -d '{"IPV6_INFO": {"IPV6INIT": "yes", "IPV6_AUTOCONF": "yes", "IPV6_DEFROUTE" : "yes"}}' 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces/enccw0.0.3a80'

{
  "reason":"GINNET0024E: Basic information of interface is missing.",
  "code":"500 Internal Server Error"
}

Right error code must be 400

**Comment by abhiramkulkarni** [comment] 2016-01-06 12:11
Duplicate of Issue #96 .

As part of this issue, i will update cfginterfaces model class with 400/404 errors for the known cases.

**Comment by danielhb** [comment] 2016-01-06 20:56
I'll close this issue because @abhiramkulkarni  will fix the issue reported here in #96 


Thanks

**Closed by danielhb** 2016-01-06 20:56 UTC
