### ISSUE TITLE
API Documentation, does not say what need to be done if user want to remove MTU parameter from network interface file

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#65] opened 2015-12-14 16:51 UTC
API Documentation, does not say what need to be done if user want to remove MTU parameter from network interface file, I have tried below options:

1) PUT call with MTU as "". However this result into issue #64.

curl -k -u <username:password>-H "Content-Type: application/json" -H "Accept: application/json"  -X PUT -d '{"BASIC_INFO":{"DEVICE":"enp0s3de","MTU":""}}' 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces/enp0s3d'
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
}                            

2) Updated to None. This update network interface file with MTU as None. Is this expected behavior, if so this needs to be updated into API documentation.

curl -k -u <username:password> -H "Content-Type: application/json" -H "Accept: application/json"  -X PUT -d '{"BASIC_INFO":{"DEVICE":"enp0s3de","MTU":"None"}}' 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces/enp0s3d'
{
  "IPV4_INFO":{
    "PEERROUTES":"\"yes\"",
    "BOOTPROTO":"\"dhcp\"",
    "DEFROUTE":"\"yes\"",
    "PEERDNS":"\"yes\"",
    "IPV4_FAILURE_FATAL":"\"no\""
  },
  "BASIC_INFO":{
    "UUID":"\"7241d3b4-2b15-49a8-994e-b788062a9b02\"",
    "MTU":"None",
    "HWADDR":"08:00:27:65:33:7F",
    "DEVICE":"enp0s3de",
    "TYPE":"Ethernet",
    "ONBOOT":"yes",
    "NAME":"enp0s3d"
  },
  "IPV6_INFO":{
    "IPV6INIT":"\"yes\"",
    "IPV6_PEERDNS":"\"yes\"",
    "IPV6_DEFROUTE":"\"yes\"",
    "IPV6_AUTOCONF":"\"yes\"",
    "IPV6_FAILURE_FATAL":"\"no\"",
    "IPV6_PEERROUTES":"\"yes\""
  }
}

3) Not providing the MTU in data will not change the value, which is expected.

**Comment by abhiramkulkarni** [comment] 2016-01-25 11:49
Issue is duplicate of #64 
Currently MTU will be always written into ifcfg file passed by the UI.
Documentation will be updated with the enahancement we decide to do on #64

**Comment by danielhb** [comment] 2016-07-07 14:29
Closing. Duplicate of #64

**Closed by danielhb** 2016-07-07 14:29 UTC
Labels: API, documentation
