### ISSUE TITLE
Network tab Home page accordion icons are not correctly displayed

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#175] opened 2016-01-12 11:28 UTC
Default accordion  effect is not showing properly on Load

**Comment by chandrureddy** [comment] 2016-01-17 16:41
What do you mean by default accordin's icons?

Since network tab content is very small, we intentionally kept both global network settings and network interfaces sections expanded.

**Comment by danielhb** [comment] 2016-07-07 16:28
I can't reproduce this in current master. Closing the issue.

**Closed by danielhb** 2016-07-07 16:28 UTC
Labels: bug, UI
