### ISSUE TITLE
NW: cfginterface GET not getting NETTYPE for s390x machine

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#132] opened 2016-01-06 13:49 UTC
1) Configured a network adapter using below curl command.
curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d {} 'https://9.152.151.67:8001/plugins/gingers390x/nwdevices/0.0.1f10/configure'
Enter host password for user 'root':
{
"status":"running",
"message":"",
"id":"29",
"target_uri":"/plugins/gingers390x/nwdevices/0.0.1f10/configure"
curl -k -u root:pass4root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/gingers390x/tasks/29'
{
"status":"finished",
"message":"Successfully configured network device 0.0.1f10",
"id":"29",
"target_uri":"/plugins/gingers390x/nwdevices/0.0.1f10/configure"
}

2) ifcfg file created with content as
DEVICE=enccw0.0.1f10
ONBOOT=yes
NETTYPE=qeth
SUBCHANNELS=0.0.1f10,0.0.1f11,0.0.1f12

3) GET is cfginterface is not giving the NETTYPE. Its a discuss call to either add TYPE as Ethernet in gingers390x while configuring network(issue #9 in gingers390x) or GET for cfginterface should return NETTYPE for s390x architecture as s390x architecture mandates NETTYPE in ifcfg file. 

curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://9.152.151.67:8001/plugins/ginger/network/cfginterfaces/enccw0.0.1f10'
Enter host password for user 'root':
{
  "IPV4_INFO":{},
  "BASIC_INFO":{
    "DEVICE":"enccw0.0.1f10",
    "ONBOOT":"yes",
    "MTU":"1500"
  },
  "IPV6_INFO":{}
}

**Comment by abhiramkulkarni** [comment] 2016-01-07 10:39
Same as #131. Duplicate of Issue #131

**Comment by danielhb** [comment] 2016-01-07 10:55
Closing this issue as it really appears to be a duplicate.

Feel free to reopen it if the solution of #131 somehow does not fix this one

**Closed by danielhb** 2016-01-07 10:55 UTC
Labels: backend, bug
