### ISSUE TITLE
NW: cfginterface PUT operation does not allow setting ipv4init to "no"

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#109] opened 2016-01-04 04:33 UTC
curl -u root -H "Content-Type: application/json" -H "Accept:application/json" -X PUT -d '{"BASIC_INFO":{"ONBOOT":"yes","DEVICE":"enp0s3d","MTU":"None"},"IPV4_INFO":{"IPV4INIT":"no"},"IPV6_INFO":{"IPV6INIT":"yes"}}' "http://localhost:8010/plugins/ginger/network/cfginterfaces/enp0s3d"
Enter host password for user 'root':
{
  "reason":"GINNET0026E: Missing ipv4 initialization key.",
  "code":"500 Internal Server Error"
}

**Comment by abhiramkulkarni** [comment] 2016-01-05 09:51
This is bug in the code. Assign this issue to me

**Comment by abhiramkulkarni** [comment] 2016-01-06 10:26
Handled "no" value also for IPV4INIT. Earlier code was considering only "yes" value.

**Comment by danielhb** [comment] 2016-01-07 10:12
A fix is available in current master. Please check if it works.

**Comment by abhiramkulkarni** [comment] 2016-01-12 11:36
This can be closed as duplicate of 110.
GET and PUT are considering the ipv4init values, but checking how to persist the ipv4 init value.

**Comment by abhiramkulkarni** [comment] 2016-01-25 12:16
Fix is working in latest upstream code. Duplicate of #110

**Closed** 2016-01-25 13:52 UTC
Labels: backend, bug
