### ISSUE TITLE
Missing group name lead to general error in ginger

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/ginger#134] opened 2016-01-06 16:42 UTC
After I get the following error:
![image](https://cloud.githubusercontent.com/assets/670087/12147978/0745d23a-b483-11e5-8a2d-c148d1435c09.png)

I checked the log and found this:
```
[05/Jan/2016:11:52:03] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/zvn/fork_daniel/wok/src/wok/control/base.py", line 351, in index
    return self.get(filter_params)
  File "/root/zvn/fork_daniel/wok/src/wok/control/base.py", line 338, in get
    resources = self._get_resources(flag_filter)
  File "/root/zvn/fork_daniel/wok/src/wok/control/base.py", line 301, in _get_resources
    res.lookup()
  File "/root/zvn/fork_daniel/wok/src/wok/control/base.py", line 146, in lookup
    self.info = lookup(*self.model_args)
  File "/root/zvn/fork_daniel/wok/src/wok/plugins/ginger/models/users.py", line 253, in lookup
    "group": grp.getgrgid(user_info.pw_gid).gr_name,
KeyError: 'getgrgid(): gid not found: 1002'
```

The code expects that the group name is always there but it isn't true:
```bash
# groups test 
test : groups: cannot find name for group ID 1002
1002
```

And due to this, no user is displayed:
![image](https://cloud.githubusercontent.com/assets/670087/12148090/a29c45ac-b483-11e5-902e-48663662a665.png)

**Comment by jrziviani** [comment] 2016-01-06 16:42
I'm working on it.

**Comment by sureshab** [comment] 2016-01-06 17:19
@jrziviani 
Since the issue is related to user management, i noticed that the users API is missing from API.md.

Also faced some issues with create and delete user when I was trying few days ago (don't remember now)
So if you could verify create and delete user, would be good :) :+1:

**Comment by jrziviani** [comment] 2016-01-06 18:41
Hello @sureshab 
I sent a fix yesterday to solve a problem related to add users (Issue #122), please check if that works for you. With theses two fixes I'm able to add and remove users.
I'll check that API.md and update the missing parts.

Thank you

**Comment by danielhb** [comment] 2016-01-07 09:45
@jrziviani patch was pushed upstream. Please verify if the fix works.

Also, you said something about updating API.md. If that's the case you can send another patch referencing this issue or create a new API.md issue and close this one.

Thanks

**Comment by jrziviani** [comment] 2016-01-07 13:02
Sent a new patch with API.md update.

thanks

**Closed** 2016-01-07 13:01 UTC
Labels: bug
