### ISSUE TITLE
service does not appear in listing post stop operation from UI

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#438] opened 2016-10-12 07:21 UTC
Host -> system services -> system service management
1. stop any services like xinetd.service or firewalld.service
2. Refresh the page 
3. Service (xinetd or firewalld) does not appear in the listing (system service management)
4. We are not able to  start the service from UI.

**Comment by sureshab** [comment] 2016-11-16 06:59
this issue is duplicate of #414

**Comment by danielhb** [comment] 2016-11-28 16:36
As @sureshab said, this is a duplicate of #414 , which was fixed/closed.

**Closed by danielhb** 2016-11-28 16:36 UTC
